#!/bin/sh

# Script Name: lynx
# Original Author: Rob Muhlestein
# Source: https://github.com/rwxrob/dot/blob/main/scripts/lynx
# Licensed under Mozilla Public License Version 2.0 (https://www.mozilla.org/en-US/MPL/2.0/)

lynxpath=/usr/bin/lynx
useragent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.79 Safari/537.1 Lynx"

if [ -e "$HOME/.config/lynx/lynx.cfg" ];then
  export LYNX_CFG="$HOME/.config/lynx/lynx.cfg"
fi

if [ -e "$HOME/.config/lynx/lynx.lss" ];then
  export LYNX_LSS="$HOME/.config/lynx/lynx.lss"
fi

if [ ! -x "$lynxpath" ]; then
  echo "Doesn't look like lynx is installed."
  exit 1
fi

exec "$lynxpath" --useragent="$useragent" "$@"
