#!/bin/sh

# Script Name: google
# Original Author: Rob Muhlestein
# Source: https://github.com/rwxrob/dot/blob/main/scripts/google
# Licensed under Mozilla Public License Version 2.0 (https://www.mozilla.org/en-US/MPL/2.0/)

url="https://google.com/search?q=$(urlencode "$*")"
exec lynx "https://google.com/search?q=$url"
