#!/usr/bin/bash

sentence_jp=$(shuf -n 1 ~/dotfiles/data/japanese_sentences.txt)
target_lang="fi"
translate_json=$(jq -n \
                    --arg q "$sentence_jp" \
                    --arg target "$target_lang" \
                    '{q: $q, target: $target}')
response_json=$(curl -sSL -X POST \
    -H "Authorization: Bearer $(gcloud auth print-access-token)" \
    -H "x-goog-user-project: teemun-aamutoivotus" \
    -H "Content-Type: application/json; charset=utf-8" \
    -d "$translate_json" \
    "https://translation.googleapis.com/language/translate/v2")
translated_sentence=$(echo "$response_json" | jq -r '.data.translations[0].translatedText')
slack_message=$(jq -n \
                    --arg sentence_jp "$sentence_jp" \
                    --arg translated_sentence "$translated_sentence" \
                    '{"text": ($sentence_jp + "\n" + $translated_sentence)}')
webhook_url=$(pass show slack/webhook_url)
curl -sSL -X POST -H 'Content-type: application/json' --data "$slack_message" "$webhook_url" >/dev/null

