[shell]
args = ["--login"]
program = "/bin/bash"

[window]
dynamic_padding = true
padding.x = 6
opacity = 0.95

[font]
size = 14.0
bold.family = "Cascadia Code PL"
bold.style = "Bold"
bold_italic.family = "Cascadia Code PL"
bold_italic.style = "Bold Italic"
italic.family = "Cascadia Code PL"
italic.style = "Italic"
normal.family = "Cascadia Code PL"
normal.style = "Regular"

[colors.primary]
background = '#282828'
foreground = '#dfbf8e'

[colors.normal]
black   = '#665c54'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e78a4e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'

[colors.bright]
black   = '#928374'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e3a84e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'
